
export const cromos = [

    {
        pais: "Qatar",
        rota: "Qatar",
        nome: "Qatar",
        imagem: require('../imgs/qatar.jpg'),
    },
    {
        pais: "Equador",
        rota: 'Equador',
        nome: 'Equador',
        imagem: require('../imgs/equador.png'),
    },
    {
        pais: "Senegal",
        rota: 'Senegal',
        nome: 'Senegal',
        imagem: require('../imgs/senegal.png'),
    },
    {
        pais: "Holanda",
        rota: 'Holanda',
        nome: 'Holanda',
        imagem: require('../imgs/holanda.jpg'),
    },
    {
        pais: "Inglaterra",
        rota: 'Inglaterra',
        nome: 'Inglaterra',
        imagem: require('../imgs/inglaterra.png'),
    },
    {
        pais: "Iran",
        rota: 'Irã',
        nome: 'Irã',
        imagem: require('../imgs/iran.png'),
    },
    {
        pais: "EUA",
        rota: 'Estados Unidos',
        nome: 'Estados Unidos',
        imagem: require('../imgs/eua.png'),
    },
    {
        pais: "País de Gales",
        rota: 'País de Gales',
        nome: 'País de Gales',
        imagem: require('../imgs/wales.png'),
    },
    {
        pais: "Argentina",
        rota: 'Argentina',
        nome: 'Argentina',
        imagem: require('../imgs/argentina.png'),
    },
    {
        pais: "Arábia Saudita",
        rota: 'Arábia Saudita',
        nome: 'Arábia Saudita',
        imagem: require('../imgs/saudi.png'),
    },
    {
        pais: "México",
        rota: 'México',
        nome: 'México',
        imagem: require('../imgs/mexico.png'),
    },
    {
        pais: "Polonia",
        rota: 'Polonia',
        nome: 'Polônia',
        imagem: require('../imgs/polonia.png'),
    },
    {
        pais: "França",
        rota: 'França',
        nome: 'França',
        imagem: require('../imgs/france.png'),
    },
    {
        pais: "Austrália",
        rota: 'Austrália',
        nome: 'Austrália',
        imagem: require('../imgs/australia.png'),
    },
    {
        pais: "Dinamarca",
        rota: 'Dinamarca',
        nome: 'Dinamarca',
        imagem: require('../imgs/dinamarca.png'),
    },
    {
        pais: "Tunisia",
        rota: 'Tunisia',
        nome: 'Tunísia',
        imagem: require('../imgs/tunisia.png'),
    },
    {
        pais: "Espanha",
        rota: 'Espanha',
        nome: 'Espanha',
        imagem: require('../imgs/spain.png'),
    },
    {
        pais: "Costa Rica",
        rota: 'Costa Rica',
        nome: 'Costa Rica',
        imagem: require('../imgs/costari.png'),
    },
    {
        pais: "Alemanha",
        rota: 'Alemanha',
        nome: 'Alemanha',
        imagem: require('../imgs/germany.png'),
    },
    {
        pais: "Japão",
        rota: 'Japão',
        nome: 'Japão',
        imagem: require('../imgs/japao.png'),
    },
    {
        pais: "Bélgica",
        rota: 'Bélgica',
        nome: 'Bélgica',
        imagem: require('../imgs/belgica.png'),
    },
    {
        pais: "Canadá",
        rota: 'Canada',
        nome: 'Canadá',
        imagem: require('../imgs/canada.png'),
    },
    {
        pais: "Marrocos",
        rota: 'Marrocos',
        nome: 'Marrocos',
        imagem: require('../imgs/marrocos.png'),
    },
    {
        pais: "Croácia",
        rota: 'Croácia',
        nome: 'Croácia',
        imagem: require('../imgs/croacia.png'),
    },
    {
        pais: "Brasil",
        rota: 'Brasil',
        nome: 'Brasil',
        imagem: require('../imgs/brasil.png'),
    },
    {
        pais: "Sérvia",
        rota: 'Sérvia',
        nome: 'Sérvia',
        imagem: require('../imgs/servia.jpg'),
    },
    {
        pais: "Suíça",
        rota: 'Suíça',
        nome: 'Suíça',
        imagem: require('../imgs/suica.png'),
    },
    {
        pais: "Camarões",
        rota: 'Camarões',
        nome: 'Camarões',
        imagem: require('../imgs/camaroes.png'),
    },
    {
        pais: "Portugal",
        rota: 'Portugal',
        nome: 'Portugal',
        imagem: require('../imgs/portugal.png'),
    },
    {
        pais: "Gana",
        rota: 'Gana',
        nome: 'Gana',
        imagem: require('../imgs/gana.png'),
    },
    {
        pais: "Uruguai",
        rota: 'Uruguai',
        nome: 'Uruguai',
        imagem: require('../imgs/uruguai.png'),
    },
    {
        pais: "Coréia do sul",
        rota: 'Coreia',
        nome: 'Coréia do Sul',
        imagem: require('../imgs/coreia.png'),
    },
    {
        pais: "Coca Cola",
        rota: 'Coca Cola',
        nome: 'Coca Cola',
        imagem: require('../imgs/coca-cola.png'),
    },
    {
        pais: "Copa do Mundo",
        rota: 'Copa do Mundo',
        nome: 'Copa do Mundo',
        imagem: require('../imgs/icon.png'),
    },
   
]